tap "domt4/autoupdate"
tap "microsoft/mssql-release"
tap "nikitabobko/tap"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Library for command-line editing
brew "readline"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Parser generator
brew "bison"
# XML-based font configuration API for X Windows
brew "fontconfig"
# Ruby environment tool
brew "chruby"
# GNU File, Shell, and Text utilities
brew "coreutils"
# General-purpose data compression with high compression ratio
brew "xz"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open-source video transcoder available for Linux, Mac, and Windows
brew "handbrake"
# Portable Foreign Function Interface library
brew "libffi"
# Generic library support script
brew "libtool"
# YAML Parser
brew "libyaml"
# Open source relational database management system
brew "mysql"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]
# Command-line interface for SQLite
brew "sqlite"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3.0"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3.5"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# Terminal multiplexer
brew "tmux"
# ODBC 3 connectivity for UNIX
brew "unixodbc"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# ODBC Driver for Microsoft(R) SQL Server(R)
brew "microsoft/mssql-release/msodbcsql18", trusted: true
# View, print, and comment on PDF documents
cask "adobe-acrobat-reader"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace", trusted: true
# Menu bar tool to limit maximum charging percentage
cask "aldente"
# Application launcher and productivity software
cask "alfred"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# File manager
cask "bloom"
# Web browser focusing on privacy
cask "brave-browser"
# Open source IDE for exploring and testing APIs
cask "bruno"
# E-books management software
cask "calibre"
# Universal database tool and SQL client
cask "dbeaver-community"
# Database manager for MySQL, PostgreSQL, SQL Server, MongoDB, SQLite and others
cask "dbgate"
# Desktop client for Ente Auth
cask "ente-auth"
cask "font-jetbrains-mono-nerd-font"
cask "font-roboto-mono"
cask "font-roboto-mono-nerd-font"
# PDF Editor
cask "foxit-pdf-editor"
# Open source API development ecosystem
cask "hoppscotch"
# Cloud backup and storage solution
cask "idrive"
# Tool to show what is persistently installed on the computer
cask "knockknock"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Clipboard manager
cask "maccy"
# Adjustable weather viewing application
cask "meteorologist"
# Cross-platform MQTT 5.0 Desktop Client
cask "mqttx"
# Web browser focused on privacy and on minimizing tracking and fingerprinting
cask "mullvad-browser"
# Interactive JavaScript, Python or SQL interface
cask "mysql-shell"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Property list and JSON editor
cask "plistedit-pro"
# Bridges Proton Mail to email clients supporting IMAP and SMTP protocols
cask "proton-mail-bridge"
# Desktop client for Proton Pass
cask "proton-pass"
# IDE for professional Python development
cask "pycharm"
# Ebook reader
cask "readest"
# PDF editor
cask "sejda-pdf"
# Instant messaging application focusing on security
cask "signal"
# Free, open-source, and completely encrypted notes app
cask "standard-notes"
# Real time file synchronisation software
cask "syncthing-app"
# Explore, create and publicly share data visualisations online
cask "tableau-public"
# Tool to explore all the running tasks (processes)
cask "taskexplorer"
# Epub reader
cask "thorium"
# To-do & task list manager
cask "ticktick"
# Web browser focusing on security
cask "tor-browser"
# Virtualiser for arm64 hardware
cask "virtualbox"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm@nightly"
# Native desktop client for WhatsApp
cask "whatsapp"
vscode "ms-azuretools.vscode-containers"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "vscodevim.vim"
