tap "domt4/autoupdate"
brew "git"
brew "neovim", args: ["HEAD"]
brew "p7zip"
brew "pinentry-mac"
cask "aldente"
cask "datweatherdoe"
cask "gpg-suite"
cask "libreoffice"
cask "lulu"
cask "mullvad-browser"
cask "tableau"
cask "virtualbox"
cask "vscodium"
